DROP TABLE IF EXISTS UserData.Item;
DROP TABLE IF EXISTS UserData.List;
DROP TABLE IF EXISTS UserData.Enduser;

DROP SCHEMA IF EXISTS UserData;

CREATE SCHEMA UserData;

CREATE TABLE IF NOT EXISTS UserData.Enduser (
    id UUID PRIMARY KEY,
    mail TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS UserData.List (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    enduser UUID NOT NULL REFERENCES UserData.Enduser(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UserData.Item (
    id SERIAL PRIMARY KEY,
    name TEXT,
    checked BOOLEAN DEFAULT FALSE,
    amount REAL,
    unit TEXT,
    list UUID NOT NULL REFERENCES UserData.List(id) ON DELETE CASCADE
);
