version: '2'

volumes:
  psdata:

services:

  postgres-db:
    container_name: postgres-db
    build: ../../.docker-images/database
    ports:
      - "5433:5432"
    volumes:
      - psdata:/var/lib/postgresql/data
    restart: always